### ISSUE TITLE
Allow multiple `notify_url`s in branch configuration

### ISSUE THREAD

**Issue by brianloveswords** [brianloveswords/hookshot#24]
Right now for the repo/branch configuration `notify_url` is an entry that accepts a single string. We should allow it to accept an array of strings so we can hit a whole bunch of notify urls.
## Related reading
- The [section of the toml spec on arrays](https://github.com/toml-lang/toml#user-content-array).
- The [toml library documentation](http://alexcrichton.com/toml-rs/toml/index.html). You'll want to look at the Value enum for operations that can be done on entries. You'll probably end up using the [`as_slice` method](http://alexcrichton.com/toml-rs/toml/enum.Value.html#method.as_slice)
- Outbound requests will block the thread they are sent on until the other side responds or hangs up. It might be nice to [spawn a new thread for each of the notification messages](http://doc.rust-lang.org/1.3.0/std/thread/) (though I would not consider this strictly necessary for acceptance of a PR).
## Some files you'll probably have to change
- [`repo_config.rs`](https://github.com/brianloveswords/hookshot/blob/master/src/repo_config.rs)
- [`notifier.rs`](https://github.com/brianloveswords/hookshot/blob/master/src/notifier.rs)

**Comment by brianloveswords** [comment]
@tkellen is this enough info?

**Comment by tkellen** [comment]
Yup!

**Comment by brianloveswords** [comment]
@tkellen rad ⚡️. Feel free to open a WIP early and ping me with any "why doesn't this compileeeeeeeeeee" questions

**Comment by tkellen** [comment]
:) will do

**Comment by brianloveswords** [comment]
OH and [the Syntax and Semantics section of The Rust Programming Language book](https://doc.rust-lang.org/stable/book/syntax-and-semantics.html) might be helpful as you start checking this out and run into unfamiliar things like `<'a>`.

**Comment by tkellen** [comment]
Just finished reading the intro book again. I did this for the first time about 9 months ago--lots of new stuff in there!

**Comment by tkellen** [comment]
resolved in #27
