### ISSUE TITLE
test_repo.tgz is empty

### ISSUE THREAD

**Issue by tkellen** [brianloveswords/hookshot#26]
```
~/code/hookshot/src/test master*
❯ tar -ztvf test_repo.tgz

~/code/hookshot/src/test master*
❯ tar -xzf test_repo.tgz

~/code/hookshot/src/test master*
❯ ls
ansible_task      basic-config.conf make_task         repo_config       test_repo.tgz
```

Can you fix this @brianloveswords?

**Comment by brianloveswords** [comment]
I just did a fresh clone and I see files in test_repo.tgz:

```
± tar -tzf test_repo.tgz
drwxr-xr-x  0 brian  staff       0 Sep 28 12:19 test_repo/
drwxr-xr-x  0 brian  staff       0 Sep 28 12:19 test_repo/.git/
-rw-r--r--  0 brian  staff      38 Sep 28 12:19 test_repo/README.md
-rw-r--r--  0 brian  staff     222 Sep 24 17:55 test_repo/.git/COMMIT_EDITMSG
-rw-r--r--  0 brian  staff     137 Sep 24 17:55 test_repo/.git/config
... rest omitted for brevity
```

And github sees it as having a filesize: https://github.com/brianloveswords/hookshot/blob/master/src/test/test_repo.tgz

Can you try recloning? Or downloading the raw file from github?

**Comment by tkellen** [comment]
Weird. Re-cloning worked. Cool. I have some work to do on our woodshed today but if I finish early I am gonna tackle #24!

**Comment by brianloveswords** [comment]
Siiiick, I think I'll be around a computer most of the afternoon so if you have questions feel free to throw them my way and I'll do my best to respond quickly

**Comment by tkellen** [comment]
Awesome!
