### ISSUE TITLE
Update requirements in readme

### ISSUE THREAD

**Issue by toddself** [brianloveswords/hookshot#31]
Tried to build this on an admittedly old version of rust (1.1.0) and get a bunch of errors compiling hyper.

Additionally El Capitan (OS X 10.11) no longer includes OpenSSL headers so you need to install them via some mechanism (and to add annoyance you need to force homebrew to link the keg since it's a library and won't do it automatically.)

See: https://github.com/sfackler/rust-openssl/issues/255

Made PR #30 for this, but not sure what minimum version of rust you want...

**Comment by brianloveswords** [comment]
closed via 2049620

**Comment by brianloveswords** [comment]
I tend to track rust stable. but I'll start including the version in the readme so people can go back in time to find a version that works if they need to.
